name: Build and Testhellow world

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Run Tests
        run: mvn test

      - name: Package Application
        run: mvn package

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: demoapp-jar
          path: target/*.jar
